language: python

python:
  - "3.5"

branches:
  only:
    - feature/feature-4-storm-detection

notifications:
  email:
    - rraavi@indiana.edu
    - srameshv@indiana.edu

sudo: false

install:
  - cd stormDetection
  - pip install Flask

script: nosetests

before_deploy:
  - cd ..
  - zip -r TeamBash_stormDetection.zip stormDetection scripts appspec.yml || true
  - mkdir -p "stormDetection"
  - mv TeamBash_stormDetection.zip stormDetection/TeamBash_stormDetection.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-teambash
    local_dir: stormDetection
    region: us-west-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      branch: feature/feature-4-storm-detection

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-teambash
    key: TeamBash_stormDetection.zip
    bundle_type: zip
    application: TeamBash-App
    deployment_group: TeamBash-App
    region: us-west-2
    on:
      branch: feature/feature-4-storm-detection

