language: python

python:
  - "3"

branches:
  only:
    - feature/feature-4-storm-detection
notifications:
  email:
    - rraavi@indiana.edu
sudo: true

install:
  - pip install -r core/python/stormDetection/requirements.txt



