language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

branches:
  only:
    - feature/feature-4-storm-detection
notifications:
  email:
    - rraavi@indiana.edu
sudo: true

install:
  - pip install -r core/python/stormDetection/requirements.txt

script: 
  - echo \TODO\


